### ISSUE TITLE
Use cross-env and esm together for gatsby-develop on windows powershell

### ISSUE THREAD

**Issue by wesbos** [wesbos/master-gatsby#28] opened 2020-09-09 16:47 UTC
Here is a tricky one I can't get working. I'm using es modules for my `gatsby-config.js` and `gatsby-node.js` files. Currently they only support common JS, so I am using the `esm` package to use import/export syntax.

The way we require `esm` is by setting `NODE_OPTIONS="-r esm"` env variable, which requires the esm package first before running `gatsby develop`. To get it working on windows, we use the [cross-env](https://www.npmjs.com/package/cross-env) package. 

So the command looks like this:

`"develop": "cross-env NODE_OPTIONS=\"-r esm\" gatsby develop",`

Works great on a mac, but with windows powershell I get `Error 10123 We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.`. This _only happens_ when there is a plugins array in `gatsby-config.js`. Taking it out solves the problem.

So to reproduce the error:

1. Make sure you are on Node >=14
2.  Clone this repo
3. Go to `finished-files/gatsby`
4. run `npm install`
5. run `npm run develop`

If you see GraphQL / Sanity errors, that is fine and means it worked. Don't worry about the site building, I just want to get past the above error. 

Not acceptable solutions:

1. Just use a `.env` file - that is introduced later in the course
2. Just use WSL. I need this to work on powershell
3. Just use docker - see above
4. LOL BUY A MAC

Ideally `npm run develop` will work on all platforms, but I'm okay with a `npm run develop:win` command. 

Things I've tried:

1. Using `set NODE_OPTIONS="-r esm" && gatsby develop` - gatsby runs in a sub-process and it doesn't seem to transfer the variable down
2. using `cross-env-shell` - it didn't work but not sure if I'm using it correctly. 

Happy to pay $250 USD to anyone who can get it running.

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:22
This is not a solution, but one thing to note is that that it tries to find a file that doesnt exist `\node_modules\\gatsby-plugin-react-helmet\\gatsby-config` 

It's got me curious now too 😆

**Comment by askkaz** [comment] 2020-09-09 17:24
yeah, the comments around similar issues mention that mac is more graceful at handling missing files than windows. I'm guessing there is some filename weirdness between windows/mac, but I'm still waiting for my old windows machine to boot/update

**Comment by wesbos** [comment] 2020-09-09 17:25
yes! and if you take out that plugin, it just errors on the next plugin. I'm bettering `esm` is doing something weird with the require path lookup

**Comment by Asjas** [comment] 2020-09-09 17:28
Removing the plugins in their entirety makes it boot up to the Gatsby GraphQL errors 👀

**Comment by wesbos** [comment] 2020-09-09 17:29
Yeah that is noted above, if you get those graphql errors, it means it's working! So what about the plugins array is making it do that..

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:35
For reference running ` $env:NODE_OPTIONS='-r esm'; npm run develop` with the `develop` command set to `"develop": "gatsby develop",`

Results in the same error as using cross env, so I don't think the issue lies with the cross env package.

**Comment by wesbos** [comment] 2020-09-09 17:37
Here is the whole stack trace from the error:

```
 ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the err
or and try again.



  Error: C:\Users\wes\Desktop\master-gatsby-master\finished-files\gatsby\node_modules\gats
  by\dist\bootstrap\get-config-file.js:1
  Error: Cannot find module 'C:\\Users\\wes\\Desktop\\master-gatsby-master\\finished-files
  \\gatsby\\node_modules\\gatsby-plugin-styled-components\\gatsby-config'
  Require stack:
  - C:\Users\wes\Desktop\master-gatsby-master\finished-files\gatsby\node_modules\gatsby\di
  st\bootstrap\get-config-file.js
  - C:\Users\wes\Desktop\master-gatsby-master\finished-files\gatsby\node_modules\gatsby\di
  st\bootstrap\index.js
  - C:\Users\wes\Desktop\master-gatsby-master\finished-files\gatsby\node_modules\gatsby\di
  st\commands\develop-process.js
  - C:\Users\wes\Desktop\master-gatsby-master\finished-files\gatsby\.cache\tmp-16336-XwaIQ
  L5eWhQb
```

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:39
Not sure if it helps but I get a slightly longer stack trace

```
 ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.



  Error: C:\Users\Daniel\master-gatsby\finished-files\gatsby\node_modules\gatsby\dist\bootstrap\get-config-file.js:1
  Error: Cannot find module 'C:\\Users\\Daniel\\master-gatsby\\finished-files\\gatsby\\node_modules\\gatsby-plugin-react-helmet\\gatsby-config'
  Require stack:
  - C:\Users\Daniel\master-gatsby\finished-files\gatsby\node_modules\gatsby\dist\bootstrap\get-config-file.js
  - C:\Users\Daniel\master-gatsby\finished-files\gatsby\node_modules\gatsby\dist\bootstrap\index.js
  - C:\Users\Daniel\master-gatsby\finished-files\gatsby\node_modules\gatsby\dist\commands\develop-process.js
  - C:\Users\Daniel\master-gatsby\finished-files\gatsby\.cache\tmp-6348-M4LsCDK3VOYP

  - v8-compile-cache.js:162 Function.require.resolve
    [gatsby]/[v8-compile-cache]/v8-compile-cache.js:162:23

  - get-config-file.js:32 getConfigFile
    [gatsby]/[gatsby]/dist/bootstrap/get-config-file.js:32:30

  - index.js:72 resolveTheme
    [gatsby]/[gatsby]/dist/bootstrap/load-themes/index.js:72:46

  - index.js:146
    [gatsby]/[gatsby]/dist/bootstrap/load-themes/index.js:146:28

  - util.js:16 tryCatcher
    [gatsby]/[bluebird]/js/release/util.js:16:23

  - reduce.js:166 Object.gotValue
    [gatsby]/[bluebird]/js/release/reduce.js:166:18

  - reduce.js:155 Object.gotAccum
    [gatsby]/[bluebird]/js/release/reduce.js:155:25

  - util.js:16 Object.tryCatcher
    [gatsby]/[bluebird]/js/release/util.js:16:23

  - promise.js:547 Promise._settlePromiseFromHandler
    [gatsby]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [gatsby]/[bluebird]/js/release/promise.js:604:18

  - promise.js:641 Promise._settlePromiseCtx
    [gatsby]/[bluebird]/js/release/promise.js:641:10

  - async.js:97 _drainQueueStep
    [gatsby]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [gatsby]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [gatsby]/[bluebird]/js/release/async.js:102:5


not finished open and validate gatsby-configs - 0.077s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slicks-slices-frontend@0.1.0 develop: `cross-env NODE_OPTIONS="-r esm" gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the slicks-slices-frontend@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2020-09-09T16_38_29_809Z-debug.log
PS C:\Users\Daniel\master-gatsby\finished-files\gatsby>







```

**Comment by Asjas** [comment] 2020-09-09 17:41
@Daniel-Griffiths It's the same stack-trace 🙂  - Wes just shortened it when he posted it here

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:41
Woops 😆

**Comment by louisjrdev** [comment] 2020-09-09 17:45
Looks like this might be the issue, might need a PR to gatsby.
https://github.com/nodejs/node/issues/31710

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:48
@louisjrdev  Yeah I noticed the same thing, the closest thing I have gotten this to work is to touch a .env and remove it later. But I know that doesnt meet the requirements 🤔

**Comment by wesbos** [comment] 2020-09-09 17:49
does putting it in a .env make it run?

**Comment by louisjrdev** [comment] 2020-09-09 17:51
See also: https://github.com/gatsbyjs/gatsby/issues/23705

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:54
@wesbos It changes the error

```
 ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.



  Error: C:\Users\Daniel\master-gatsby\finished-files\gatsby\gatsby-config.js:1
  (function (exports, require, module, __filename, __dirname) { import dotenv from 'dotenv';
                                                                                                    ^^^^^^
  SyntaxError: Cannot use import statement outside a module
```

Looks the error shifts from gatbsy config, and it looks like esm is not even enabled when using a `.env` file. Hmm.

**Comment by louisjrdev** [comment] 2020-09-09 17:54
I think it's less a "make ESM work with gatsby issue" than it is a "gatsby doesn't support esm fully yet".

**Comment by wesbos** [comment] 2020-09-09 17:55
That error means `-r esm` isn't being used at all

@louisjrdev to be clear, this is using the `esm` package, _not_ the built in node.js esm experimental esm

**Comment by Daniel-Griffiths** [comment] 2020-09-09 17:55
@louisjrdev  It got it working in the past by using Typescript but that's waaay out of scope for this 😅

**Comment by wesbos** [comment] 2020-09-09 17:57
Someone on twitter mentioned it works if you create an empty gatsby-config.js file in each plugin. 

So - why is gatsby looking for a config file in the plugin that doesn't exist?

**Comment by ejdigby** [comment] 2020-09-09 18:00
FYI you also get to the same point as @Daniel-Griffiths by replacing `NODE_OPTIONS=\"-r esm\"` with `NODE_OPTIONS=$(\"-r esm\")`.

Potential gets you slightly further without having to use a `.env` file

**Comment by wesbos** [comment] 2020-09-09 18:02
That point isn't any further, I think that method doesn't expose the NODE_OPTIONS value to the child process and thus `esm` package is completely ignored.

**Comment by ejdigby** [comment] 2020-09-09 18:05
So if you run the following you can see (I think) that the child process does get the env variable, its just a problem with how handled after that:

test.js
```
console.log(process.env.NODE_OPTIONS)
```

package.json
```
"develop": "cross-env NODE_OPTIONS=\"-r esm\" node test.js",
```

output 
```
-r esm
```

Apologies if it doesn't show what I think it shows

**Comment by Daniel-Griffiths** [comment] 2020-09-09 18:05
Ok I got it working but the solution is a little nasty. Gimme a sec to write the solution...

**Comment by louisjrdev** [comment] 2020-09-09 18:09
Oooh I have it working too

**Comment by Daniel-Griffiths** [comment] 2020-09-09 18:09
So in the path 

```
node_modules/gatsby/dist/bootstrap/get-config-file.js
```

Go to line 40 

![image](https://user-images.githubusercontent.com/1458314/92636677-ab0b0680-f2cf-11ea-8076-df93a2ef0dbc.png)

And remove the code in that if statement so it looks like this: 

![image](https://user-images.githubusercontent.com/1458314/92636737-c37b2100-f2cf-11ea-8663-9c0e453a7a04.png)

Then I used patch-package to persists the fix: https://www.npmjs.com/package/patch-package

<img src="https://user-images.githubusercontent.com/1458314/92636866-fde4be00-f2cf-11ea-9be3-d21d73615a76.png" width="300"/>

**Comment by wesbos** [comment] 2020-09-09 18:10
Ah! I was just looking at this: https://github.com/gatsbyjs/gatsby/issues/17008

I wonder if Gatsby can be patched then?

**Comment by louisjrdev** [comment] 2020-09-09 18:11
@wesbos Okay so i think I have solved this, without modifying any node modules.

So in the gatsby-config.js make it:
```
module.exports = {
  pathPrefix: '/pizza',
  siteMetadata: {
    title: `Slicks Slices`,
    siteUrl: 'https://gatsby.pizza',
    description: 'The best pizza place in Hamilton!',
    twitter: '@slicksSlices',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',
    {
      // this is the name of the plugin you are adding
      resolve: 'gatsby-source-sanity',
      options: {
        projectId: '0jfvvkkd',
        dataset: 'production',
        watchMode: true,
        token: process.env.SANITY_TOKEN,
      },
    },
  ],
};
```

Follow the instructions here:
https://github.com/gatsbyjs/gatsby/issues/7810#issuecomment-449741977

change the `develop` script in the package.json to just `gatsby develop`

**Comment by louisjrdev** [comment] 2020-09-09 18:12
A bit hacky but it works, not sure if it does on mac / linux

**Comment by wesbos** [comment] 2020-09-09 18:13
@louisjrdev thanks but that is removing all the ES Modules and just reverting it back to commonJS. So it gets rid of the problem, but also the feature :)

**Comment by Daniel-Griffiths** [comment] 2020-09-09 18:15
Besides the above I can't find any other way to get this working. I think someone needs to submit a patch to Gatsby and find a real fix instead of deleting the problem 😆 

patch-package has worked great for me in the past but I understand it's not the kind of thing you want to use on a course.

**Comment by wesbos** [comment] 2020-09-09 18:16
Got it running based on @Daniel-Griffiths and this thread: https://github.com/gatsbyjs/gatsby/issues/17008
 
If I crack open `node_modules/gatsby/dist/utils/test-require-error.js` and replace this:

```
const firstLine = err.toString().split(`\n`)[0];
```

with this:

```
const firstLine = err.toString().replace(/\\\\/g, '\\').split(`\n`)[0];
```

It builds!  So it's an issue with gatsby.. Perhaps they would fancy a PR

**Comment by Asjas** [comment] 2020-09-09 18:19
Yeah, If I do the same it work on Windows so I can confirm that seems to be the fix to build it, and I tested on MacOS and it's still working there as well after I change it there. 👍

**Comment by Daniel-Griffiths** [comment] 2020-09-09 18:20
I will submit a PR to gatsby shortly, then we wait... 👀

**Comment by wesbos** [comment] 2020-09-09 18:21
https://github.com/gatsbyjs/gatsby/pull/26840 PR

**Comment by Daniel-Griffiths** [comment] 2020-09-09 18:21
Beat me to it 😆

**Comment by askkaz** [comment] 2020-09-09 18:24
its surprising to me that this isn't a more common issue, right?

**Comment by wesbos** [comment] 2020-09-09 18:27
Yeah - very bizarre. It might have something to do with esm changing how paths reported? Not sure what it does under the hood. There were a few reports of it happening in gatsby, and none in esm though.

**Comment by Daniel-Griffiths** [comment] 2020-09-09 18:30
@askkaz I guess most people end up sticking with commonjs as it's the default. 🤷‍♂️

I saw various articles and github threads trying to find a solution, but a lot of the fixes seem outdated and no longer work.

**Closed** 2020-09-10 19:16 UTC

**Comment by Daniel-Griffiths** [comment] 2020-09-10 22:20
Awesome thanks @wesbos!  :slightly_smiling_face: 

Will shoot you a email from `daniel.griffiths.jobs@gmail.com`
